// <auto-generated />
using System;
using APBD_PJATK_Cw4_s29764.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_PJATK_Cw4_s29764.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525200604_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_PJATK_Cw4_s29764.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "I5-12400",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "6 rdzeni, 12 wątków, do 4.4 GHz, 18MB cache",
                            Name = "Intel Core i5-12400"
                        },
                        new
                        {
                            Code = "RTX4070",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 2,
                            Description = "12GB GDDR6X, 5888 CUDA cores",
                            Name = "NVIDIA GeForce RTX 4070"
                        },
                        new
                        {
                            Code = "DDR4-32",
                            ComponentManufacturersId = 4,
                            ComponentTypesId = 3,
                            Description = "CL16, 1.35V",
                            Name = "Kingston Fury Beast 32GB (2x16GB) DDR4-3200"
                        },
                        new
                        {
                            Code = "SSD-1TB",
                            ComponentManufacturersId = 4,
                            ComponentTypesId = 4,
                            Description = "NVMe PCIe 4.0, do 7450 MB/s",
                            Name = "Samsung 990 PRO 1TB"
                        },
                        new
                        {
                            Code = "B760-A",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 5,
                            Description = "Socket LGA 1700, DDR5, PCIe 5.0",
                            Name = "ASUS Prime B760-PLUS"
                        });
                });

            modelBuilder.Entity("APBD_PJATK_Cw4_s29764.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INTEL",
                            FoundationDate = new DateOnly(1968, 7, 18),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateOnly(1969, 5, 1),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NVIDIA",
                            FoundationDate = new DateOnly(1993, 4, 5),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "SAMSUNG",
                            FoundationDate = new DateOnly(1969, 1, 13),
                            FullName = "Samsung Electronics"
                        });
                });

            modelBuilder.Entity("APBD_PJATK_Cw4_s29764.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Procesor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Karta graficzna"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Pamięć RAM"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "SSD",
                            Name = "Dysk SSD"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "MB",
                            Name = "Płyta główna"
                        });
                });

            modelBuilder.Entity("APBD_PJATK_Cw4_s29764.Models.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast",
                            Stock = 8,
                            Warranty = 36,
                            Weight = 14.8f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Pro",
                            Stock = 15,
                            Warranty = 24,
                            Weight = 9.2f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Creator Ultra",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 16.5f
                        });
                });

            modelBuilder.Entity("APBD_PJATK_Cw4_s29764.Models.PcComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PcComponents", (string)null);

                    b.HasData(
                        new
                        {
                            PcId = 1,
                            ComponentCode = "I5-12400",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "RTX4070",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "DDR4-32",
                            Amount = 2
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "SSD-1TB",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "B760-A",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "I5-12400",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "DDR4-32",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "SSD-1TB",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "B760-A",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "RTX4070",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "DDR4-32",
                            Amount = 2
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "SSD-1TB",
                            Amount = 2
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "B760-A",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("APBD_PJATK_Cw4_s29764.Models.Component", b =>
                {
                    b.HasOne("APBD_PJATK_Cw4_s29764.Models.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_PJATK_Cw4_s29764.Models.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("APBD_PJATK_Cw4_s29764.Models.PcComponent", b =>
                {
                    b.HasOne("APBD_PJATK_Cw4_s29764.Models.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_PJATK_Cw4_s29764.Models.Pc", "Pc")
                        .WithMany("PcComponents")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("APBD_PJATK_Cw4_s29764.Models.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("APBD_PJATK_Cw4_s29764.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("APBD_PJATK_Cw4_s29764.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("APBD_PJATK_Cw4_s29764.Models.Pc", b =>
                {
                    b.Navigation("PcComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
